# Chinese translations for Rubisco package
# Rubisco 软件包的简体中文翻译.
# Copyright (C) 2025 The C++ Plus Project.
# This file is part of the Rubisco.
#
# Rubisco is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Rubisco is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: Rubisco 0.1.0\n"
"Report-Msgid-Bugs-To: cpppteam@email.cn\n"
"POT-Creation-Date: 2025-08-11 20:29+0800\n"
"PO-Revision-Date: 2024-06-25 11:07+0800\n"
"Last-Translator:  <wushengwuxi-msctinoulk@outlook.com>\n"
"Language-Team: Chinese (simplified) <i18n-zh@googlegroups.com>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../rubisco/kernel/project_config/hook.py:75
msgid "Hook '${{name}}' is invalid."
msgstr "无效的钩子 '${{name}}' 。"

#: ../rubisco/kernel/project_config/hook.py:79
msgid "A workflow [yellow]must[/yellow] contain at least 'exec', 'run' or 'workflow'."
msgstr "一个工作流 [yellow]必须[/yellow] 至少包含 'exec'、'run' 或 'workflow'。"

#: ../rubisco/kernel/project_config/project_config.py:86
msgid "The minimum version of rubisco required by the project [underline][link=${{uri}}]${{name}}[/link][/underline]' is '[cyan]${{version}}[/cyan]'."
msgstr "项目 [underline][link=${{uri}}]${{name}}[/link][/underline] 要求 rubisco 的最低版本是 '[cyan]${{version}}[/cyan]'。"

#: ../rubisco/kernel/project_config/project_config.py:93
#: ../rubisco/kernel/workflow/step.py:92
#: ../rubisco/kernel/workflow/workflow.py:150
#: ../rubisco/kernel/workflow/workflow.py:151
msgid "<Unnamed>"
msgstr "<未命名>"

#: ../rubisco/kernel/project_config/project_config.py:97
msgid "Please upgrade rubisco to the required version."
msgstr "请升级 rubisco 到所需版本。"

#: ../rubisco/kernel/project_config/project_config.py:108
msgid "Project configuration file '${{path}}' is not found."
msgstr "项目配置文件 '${{path}}' 未找到。"

#: ../rubisco/kernel/project_config/project_config.py:164
msgid "Hooks must be a dictionary."
msgstr "钩子必须是一个字典。"

#: ../rubisco/kernel/command_event/event_file_data.py:84
msgid "Invalid args count of EventFileData: ${{ data }}"
msgstr "EventFileData 的无效参数计数：${{ data }}"

#: ../rubisco/kernel/command_event/event_types.py:60
msgid "Directory"
msgstr "目录"

#: ../rubisco/kernel/command_event/event_types.py:62
msgid "File"
msgstr "文件"

#: ../rubisco/kernel/command_event/event_types.py:64
msgid "Alias"
msgstr "别名"

#: ../rubisco/kernel/command_event/event_types.py:66
msgid "Mount point"
msgstr "挂载点"

#: ../rubisco/kernel/command_event/args.py:76
msgid "Missing required option: ${{name}}."
msgstr "缺少必需的选项：${{name}}。"

#: ../rubisco/kernel/command_event/args.py:78
msgid "Missing required argument: ${{name}}."
msgstr "缺少必需的参数：${{name}}。"

#: ../rubisco/kernel/command_event/args.py:84
#: ../rubisco/kernel/command_event/args.py:111
msgid "The option `${{name}}` is not the type `${{type}}`."
msgstr "选项 `${{name}}` 不是类型 `${{type}}`。"

#: ../rubisco/kernel/command_event/args.py:86
#: ../rubisco/kernel/command_event/args.py:113
msgid "The argument `${{name}}` is not the type `${{type}}`."
msgstr "参数 `${{name}}` 不是类型 `${{type}}`。"

#: ../rubisco/kernel/command_event/args.py:125
msgid "The option `${{name}}` is readonly now."
msgstr "选项 `${{name}}` 现在是只读的。"

#: ../rubisco/kernel/command_event/args.py:127
#: ../rubisco/kernel/command_event/args.py:286
msgid "The argument `${{name}}` is readonly now."
msgstr "参数 `${{name}}` 现在是只读的。"

#: ../rubisco/kernel/command_event/args.py:252
msgid "The minimum count of `${{name}}` must be greater than or equal to 0."
msgstr "`${{name}}` 的最小计数必须大于或等于 0。"

#: ../rubisco/kernel/command_event/args.py:262
msgid "The maximum count of `${{name}}` must be greater than the minimum count of `${{name}}`."
msgstr "`${{name}}` 的最大计数必须大于 `${{name}}` 的最小计数。"

#: ../rubisco/kernel/command_event/cmd_event.py:224
#: ../rubisco/kernel/command_event/cmd_event.py:242
#: ../rubisco/kernel/command_event/cmd_event.py:260
#: ../rubisco/kernel/command_event/cmd_event.py:278
#: ../rubisco/kernel/command_event/cmd_event.py:296
#: ../rubisco/kernel/command_event/cmd_event.py:318
msgid "The node ${{name}} is not a event directory."
msgstr "节点 ${{name}} 不是事件目录。"

#: ../rubisco/kernel/command_event/cmd_event.py:380
msgid "The option ${{name}} does not exist."
msgstr "选项 ${{name}} 不存在。"

#: ../rubisco/kernel/command_event/cmd_event.py:394
msgid "The node ${{name}} is not a file."
msgstr "节点 ${{name}} 不是文件。"

#: ../rubisco/kernel/command_event/cmd_event.py:412
msgid "The number of arguments is less than ${{mincount}}."
msgstr "参数个数少于 ${{mincount}}。"

#: ../rubisco/kernel/command_event/cmd_event.py:420
msgid "The number of arguments is more than ${{maxcount}}."
msgstr "参数个数多于 ${{maxcount}}。"

#: ../rubisco/kernel/command_event/cmd_event.py:457
#: ../rubisco/kernel/command_event/event_path.py:120
#: ../rubisco/kernel/command_event/event_path.py:293
msgid "Not a directory: ${{path}}."
msgstr "不是目录：${{path}}。"

#: ../rubisco/kernel/command_event/cmd_event.py:499
msgid "The number of arguments is not correct. Expected ${{expected}}, got ${{got}}."
msgstr "参数个数不正确。期望 ${{expected}}，得到 ${{got}}。"

#: ../rubisco/kernel/command_event/cmd_event.py:534
msgid "The node ${{path}} is not a file."
msgstr "节点 ${{path}} 不是文件。"

#: ../rubisco/kernel/command_event/event_path.py:145
#: ../rubisco/kernel/command_event/event_path.py:278
msgid "No such event: ${{path}}."
msgstr "没有这个的事件：${{path}}。"

#: ../rubisco/kernel/command_event/event_path.py:284
msgid "Rubisco command event filesystem does not support recursive creation of directories. You must create the parent directory first because you must set the description explicitly."
msgstr "Rubisco 命令事件文件系统不支持递归创建目录。您必须先创建父目录，因为您必须明确设置描述。"

#: ../rubisco/kernel/command_event/event_path.py:329
#: ../rubisco/kernel/command_event/event_path.py:379
#: ../rubisco/kernel/command_event/event_path.py:448
#: ../rubisco/kernel/command_event/event_path.py:482
msgid "File exists: ${{path}}"
msgstr "文件已存在：${{path}}"

#: ../rubisco/kernel/command_event/event_path.py:426
msgid "Not a file: ${{path}}"
msgstr "不是文件：${{path}}"

#: ../rubisco/kernel/command_event/cefs_fstab.py:79
msgid "Parsing failed: {{line}}"
msgstr "解析失败：{{line}}"

#: ../rubisco/kernel/command_event/register.py:58
msgid "You can only register callbacks to files."
msgstr "你只能给文件注册回调函数"

#: ../rubisco/kernel/command_event/register.py:68
msgid "You must register callbacks to files."
msgstr "你必须给文件注册回调函数。"

#: ../rubisco/kernel/mirrorlist.py:146
msgid "Recursion detected in mirrorlist: '${{name}}'"
msgstr "检测到镜像列表中的递归: '${{name}}'"

#: ../rubisco/kernel/mirrorlist.py:150
msgid "Please check your [underline]mirrorlist.json[/underline] file in workspace, user or global config directory."
msgstr "请检查工作区、用户或全局配置目录中的 [underline]mirrorlist.json[/underline] 文件。"

#: ../rubisco/kernel/mirrorlist.py:197
msgid "All mirrors are unreachable or canceled. Switching to official [underline][blue]${{url}}[/blue][/underline] ..."
msgstr "所有镜像都无法访问或已取消。切换到 official [underline][blue]${{url}}[/blue][/underline] ..."

#: ../rubisco/kernel/mirrorlist.py:206 ../rubisco/lib/l10n.py:79
#: ../rubisco/envutils/env.py:250
msgid "Unknown"
msgstr "未知"

#: ../rubisco/kernel/mirrorlist.py:257
msgid "Mirror '${{p}}/${{site}}/${{mirror}}' not found."
msgstr "镜像 '${{p}}/${{site}}/${{mirror}}' 未找到。"

#: ../rubisco/kernel/mirrorlist.py:269
msgid "Mirror '${{mirror}}' is not a string."
msgstr "镜像 '${{mirror}}' 不是字符串。"

#: ../rubisco/kernel/mirrorlist.py:284
msgid "Source '${{protocol}}/${{website}}/${{name}}' not found."
msgstr "源 '${{protocol}}/${{website}}/${{name}}' 未找到。"

#: ../rubisco/kernel/workflow/__init__.py:61
msgid "Step type '${{name}}' registered multiple times. This may cause unexpected behavior. It's unsafe."
msgstr "步骤类型 '${{name}}' 注册了多次。这可能导致意外行为。这是不安全的。"

#: ../rubisco/kernel/workflow/__init__.py:109
msgid "Workflow running failed: ${{exc}}"
msgstr "工作流运行失败: ${{exc}}"

#: ../rubisco/kernel/workflow/__init__.py:159
msgid "The suffix of ${{path}} is invalid."
msgstr "${{path}} 的后缀无效。"

#: ../rubisco/kernel/workflow/__init__.py:164
msgid "We only support '.json', '.json5', '.yaml', '.yml'."
msgstr "我们只支持 '.json', '.json5', '.yaml', '.yml'。"

#: ../rubisco/kernel/workflow/step.py:90
msgid "Step '${{step}}' failed: ${{exc}}"
msgstr "步骤 '${{step}}' 失败： ${{exc}}"

#: ../rubisco/kernel/workflow/steps/glob.py:65
#: ../rubisco/kernel/workflow/steps/glob.py:75
msgid "The glob item must be a string."
msgstr "通配符项必须是字符串。"

#: ../rubisco/kernel/workflow/steps/matrix.py:80
msgid "Matrix variables must be a dict."
msgstr "矩阵变量必须是字典。"

#: ../rubisco/kernel/workflow/steps/compress.py:74
msgid "Compress format must be a list of string or a string."
msgstr "压缩格式必须是字符串或字符串列表。"

#: ../rubisco/kernel/workflow/steps/remove.py:54
msgid "The remove item must be a string."
msgstr "删除项必须是一个字符串。"

#: ../rubisco/kernel/workflow/steps/mkdir.py:52
msgid "The paths must be a list of strings."
msgstr "多个路径必须是一个字符串列表。"

#: ../rubisco/kernel/workflow/steps/copyfile.py:61
msgid "The copy item must be a string."
msgstr "复制文件名必须是字符串类型。"

#: ../rubisco/kernel/workflow/steps/copyfile.py:109
msgid "No file matched the glob pattern: ${{glob}}."
msgstr "没有文件匹配通配符模式: ${{glob}}。"

#: ../rubisco/kernel/workflow/workflow.py:103
msgid "Step id '${{step_id}}' is duplicated."
msgstr "步骤 '${{step_id}}' 的 ID 重复。"

#: ../rubisco/kernel/workflow/workflow.py:127
msgid "Unknown step type: '${{step_type}}' of step '${{step_name}}'. Please check the workflow."
msgstr "未知的步骤类型: '${{step_type}}' 的步骤 '${{step_name}}'。请检查工作流。"

#: ../rubisco/kernel/workflow/workflow.py:136
msgid "Consider use 'type' attribute manually."
msgstr "考虑手动指定 'type' 属性。"

#: ../rubisco/kernel/workflow/workflow.py:144
msgid "The type of step '${{step}}'[black](${{step_id}})[/black] in workflow '${{workflow}}'[black](${{workflow_id}})[/black] is not provided and could not be inferred."
msgstr "工作流 '${{workflow}}'[black](${{workflow_id}})[/black] 中的步骤 '${{step}}'[black](${{step_id}})[/black] 的类型未被提供，且无法推断。"

#: ../rubisco/kernel/git.py:53
msgid "Checking out files"
msgstr "正在检出文件"

#: ../rubisco/kernel/git.py:55
msgid "Compressing objects"
msgstr "正在压缩对象"

#: ../rubisco/kernel/git.py:57
msgid "Counting objects"
msgstr "正在计数对象"

#: ../rubisco/kernel/git.py:59
msgid "Finding sources"
msgstr "正在查找源"

#: ../rubisco/kernel/git.py:61
msgid "Receiving objects"
msgstr "正在接收对象"

#: ../rubisco/kernel/git.py:63
msgid "Resolving deltas"
msgstr "正在解析增量"

#: ../rubisco/kernel/git.py:65
msgid "Writing objects"
msgstr "正在写入对象"

#: ../rubisco/kernel/git.py:146
msgid "Repository ${{path}} not found."
msgstr "仓库 ${{path}} 未找到。"

#: ../rubisco/kernel/git.py:158
msgid "Repository ${{path}} is not a git repository."
msgstr "仓库 ${{path}} 不是一个 git 仓库。"

#: ../rubisco/kernel/git.py:188 ../rubisco/kernel/git.py:256
msgid "Git operation failed: ${{exc}}"
msgstr "Git 操作失败: ${{exc}}"

#: ../rubisco/kernel/git.py:225
msgid "Repository ${{path}} already exists."
msgstr "仓库 ${{path}} 已存在。"

#: ../rubisco/kernel/config_loader.py:82
msgid "Unknown file type: ${{path}}"
msgstr "未知的文件类型: ${{path}}"

#: ../rubisco/lib/convert.py:133
msgid "Cannot convert value ${{value}} to type ${{type}}"
msgstr "无法将值 ${{value}} 转换为类型 ${{type}}"

#: ../rubisco/lib/wget.py:71
msgid "Downloading ${{url}} ..."
msgstr "正在下载 ${{url}} ..."

#: ../rubisco/lib/wget.py:74
msgid "Download"
msgstr "下载"

#: ../rubisco/lib/sqlite_strerror.py:137
msgid "Success."
msgstr "成功。"

#: ../rubisco/lib/sqlite_strerror.py:139
msgid "SQL error or missing database."
msgstr "SQL 错误或缺少数据库。"

#: ../rubisco/lib/sqlite_strerror.py:141
msgid "Internal logic error in SQLite."
msgstr "SQLite 内部逻辑错误。"

#: ../rubisco/lib/sqlite_strerror.py:143
msgid "Access permission denied."
msgstr "访问权限被拒绝。"

#: ../rubisco/lib/sqlite_strerror.py:145
msgid "Callback routine requested an abort."
msgstr "回调例程请求中止。"

#: ../rubisco/lib/sqlite_strerror.py:147
msgid "The database file is locked."
msgstr "数据库文件被锁定。"

#: ../rubisco/lib/sqlite_strerror.py:149
msgid "A table in the database is locked."
msgstr "数据库中的一个表被锁定。"

#: ../rubisco/lib/sqlite_strerror.py:151
msgid "Memory allocation/reallocation failed."
msgstr "内存分配/重新分配失败。"

#: ../rubisco/lib/sqlite_strerror.py:153
msgid "Attempt to write a readonly database."
msgstr "尝试写入只读数据库。"

#: ../rubisco/lib/sqlite_strerror.py:155
msgid "Operation terminated by sqlite3_interrupt()."
msgstr "操作被 sqlite3_interrupt() 终止。"

#: ../rubisco/lib/sqlite_strerror.py:157
msgid "I/O error."
msgstr "输入/输出错误。"

#: ../rubisco/lib/sqlite_strerror.py:159
msgid "The database file has been corrupted."
msgstr "数据库文件已损坏。"

#: ../rubisco/lib/sqlite_strerror.py:161
msgid "Insertion failed because database is full."
msgstr "插入失败，因为数据库已满。"

#: ../rubisco/lib/sqlite_strerror.py:163
msgid "Unable to open the database file."
msgstr "无法打开数据库文件。"

#: ../rubisco/lib/sqlite_strerror.py:165
msgid "Database file is malformed."
msgstr "数据库文件格式错误。"

#: ../rubisco/lib/sqlite_strerror.py:170
msgid "The database schema changed."
msgstr "数据库模式已更改。"

#: ../rubisco/lib/sqlite_strerror.py:172
msgid "String or BLOB was too large."
msgstr "字符串或 BLOB 太大。"

#: ../rubisco/lib/sqlite_strerror.py:174
msgid "Abort due to constraint violation."
msgstr "由于约束违规而中止。"

#: ../rubisco/lib/sqlite_strerror.py:176
msgid "Data type mismatch."
msgstr "数据类型不匹配。"

#: ../rubisco/lib/sqlite_strerror.py:178
msgid "Library used incorrectly."
msgstr "库使用不正确。"

#: ../rubisco/lib/sqlite_strerror.py:180
msgid "No large file support."
msgstr "没有大文件支持。"

#: ../rubisco/lib/sqlite_strerror.py:182
msgid "Illegal authorization request."
msgstr "非法的授权请求。"

#: ../rubisco/lib/sqlite_strerror.py:187
msgid "2nd parameter to sqlite3_bind out of range."
msgstr "第二个参数超出范围。"

#: ../rubisco/lib/sqlite_strerror.py:189
msgid "File opened that is not a database file."
msgstr "打开的文件不是数据库文件。"

#: ../rubisco/lib/sqlite_strerror.py:191
msgid "Another row of output is available."
msgstr "另一行输出可用。"

#: ../rubisco/lib/sqlite_strerror.py:193
msgid "An operation is completed."
msgstr "操作已完成。"

#: ../rubisco/lib/sqlite_strerror.py:196
msgid "An SQL statement could not be prepared because a collating sequence named in that SQL statement could not be located."
msgstr "一个 SQL 语句无法准备，因为在该 SQL 语句中命名的排序序列无法找到。"

#: ../rubisco/lib/sqlite_strerror.py:201
msgid "Operation could not continue because another process is busy recovering a WAL mode database file following a crash."
msgstr "由于另一个进程正在忙于恢复崩溃后的 WAL 模式数据库文件，操作无法继续。"

#: ../rubisco/lib/sqlite_strerror.py:206
msgid "Access to an SQLite data record is blocked by another database connection that is using the same record in shared cache mode."
msgstr "另一个数据库连接正在使用共享缓存模式中的相同记录，阻止对 SQLite 数据记录的访问。"

#: ../rubisco/lib/sqlite_strerror.py:212
msgid "A WAL mode database cannot be opened because the database file needs to be recovered and recovery requires write access but only read access is available."
msgstr "一个 WAL 模式数据库无法打开，因为数据库文件需要恢复，而恢复需要写访问权限，但只有读访问权限可用。"

#: ../rubisco/lib/sqlite_strerror.py:218
msgid "Hardware malfunction or a filesystem came unmounted while the file was open."
msgstr "硬件故障或文件系统在文件打开时卸载。"

#: ../rubisco/lib/sqlite_strerror.py:222
msgid "Content in the virtual table is corrupt."
msgstr "虚拟表中的内容损坏。"

#: ../rubisco/lib/sqlite_strerror.py:227
msgid "A CHECK constraint failed."
msgstr "一个 CHECK 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:230
msgid "An operation was attempted on a database for which the logged in user lacks sufficient authorization."
msgstr "尝试对一个数据库进行操作，但登录的用户缺乏足够的授权。"

#: ../rubisco/lib/sqlite_strerror.py:234
msgid "A WAL mode database file has been recovered."
msgstr "一个 WAL 模式数据库文件已经恢复。"

#: ../rubisco/lib/sqlite_strerror.py:237
msgid "An SQL statement aborted because the transaction that was active when the SQL statement first started was rolled back."
msgstr "一个 SQL 语句中止，因为在 SQL 语句首次启动时活动的事务被回滚。"

#: ../rubisco/lib/sqlite_strerror.py:242
msgid "A WAL mode database connection tries to promote a read transaction into a write transaction but finds that another database connection has already written to the database and thus invalidated prior reads."
msgstr "一个 WAL 模式数据库连接试图将一个读事务提升为写事务，但发现另一个数据库连接已经写入了数据库，从而使之前的读取无效。"

#: ../rubisco/lib/sqlite_strerror.py:249
msgid "Virtual table implementations cannot complete the current operation because of locks held by other threads or processes."
msgstr "由于其他线程或进程持有的锁，虚拟表实现无法完成当前操作。"

#: ../rubisco/lib/sqlite_strerror.py:254
msgid "SQLite is unable to obtain a read lock on a WAL mode database because the shared-memory file associated with that database is read-only."
msgstr "由于与该数据库关联的共享内存文件是只读的，SQLite 无法在 WAL 模式数据库上获取读锁。"

#: ../rubisco/lib/sqlite_strerror.py:260
msgid "A read attempt in the VFS layer was unable to obtain as many bytes as was requested."
msgstr "VFS 层的读取尝试无法获得所请求的字节数。"

#: ../rubisco/lib/sqlite_strerror.py:264
msgid "The schema of the sqlite_sequence table is corrupt."
msgstr "sqlite_sequence 表的模式损坏。"

#: ../rubisco/lib/sqlite_strerror.py:267
msgid "A file failed to open because the file is really a directory."
msgstr "文件打开失败，因为文件实际上是一个目录。"

#: ../rubisco/lib/sqlite_strerror.py:271
msgid "A commit hook callback returned non-zero that thus caused the SQL statement to be rolled back."
msgstr "一个提交钩子回调返回了非零值，导致 SQL 语句被回滚。"

#: ../rubisco/lib/sqlite_strerror.py:275
msgid "The historical snapshot is no longer available."
msgstr "历史快照不再可用。"

#: ../rubisco/lib/sqlite_strerror.py:278
msgid "A blocking POSIX advisory file lock request in the VFS layer failed due to a timeout."
msgstr "一个在 VFS 层的阻塞 POSIX 咨询文件锁请求由于超时而失败。"

#: ../rubisco/lib/sqlite_strerror.py:283
msgid "A database cannot be opened because it has a hot journal that needs to be rolled back but cannot because the database is readonly."
msgstr "数据库无法打开，因为它有一个需要回滚的热日志，但无法回滚，因为数据库是只读的。"

#: ../rubisco/lib/sqlite_strerror.py:289
msgid "An I/O error occured in the VFS layer while trying to write into a file on disk."
msgstr "尝试在磁盘上的文件中写入时，VFS 层中发生了 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:293
msgid "SQLite detected an entry is or was missing from an index."
msgstr "SQLite 检测到一个条目在索引中缺失或已缺失。"

#: ../rubisco/lib/sqlite_strerror.py:296
msgid "A file open operation failed because the operating system was unable to convert the filename into a full pathname."
msgstr "文件打开操作失败，因为操作系统无法将文件名转换为完整路径名。"

#: ../rubisco/lib/sqlite_strerror.py:300
msgid "A foreign key constraint failed."
msgstr "一个外键约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:303
msgid "A database cannot be modified because the database file has been moved since it was opened."
msgstr "数据库无法修改，因为数据库文件在打开后已经移动。"

#: ../rubisco/lib/sqlite_strerror.py:308 ../rubisco/lib/sqlite_strerror.py:316
msgid "An I/O error occured in the VFS layer while trying to fsync."
msgstr "尝试 fsync 时发 VFS 层中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:311
msgid "cygwin_conv_path() failed."
msgstr "cygwin_conv_path() 失败。"

#: ../rubisco/lib/sqlite_strerror.py:313
msgid "A function constraint failed."
msgstr "一个函数约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:322
msgid "A NOT NULL constraint failed."
msgstr "一个 NOT NULL 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:325
msgid "The database is read-only because process does not have permission to create a journal file in the same directory as the database and the creation of a journal file is a prerequisite for writing."
msgstr "数据库是只读的，因为进程没有权限在与数据库相同的目录中创建日志文件，而创建日志文件是写入的先决条件。"

#: ../rubisco/lib/sqlite_strerror.py:332
msgid "I/O error in the VFS layer while trying to truncate a file to a smaller size."
msgstr "在尝试将文件截断为较小大小时，VFS 层中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:337
msgid "SQLITE_OPEN_NOFOLLOW is used but the database file is a symlink."
msgstr "SQLITE_OPEN_NOFOLLOW 被使用，但数据库文件是一个符号链接。"

#: ../rubisco/lib/sqlite_strerror.py:340
msgid "A PRIMARY KEY constraint failed."
msgstr "一个 PRIMARY KEY 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:343
msgid "An I/O error occured in the VFS layer while trying to invoke fstat() (or the equivalent) on a file in order to determine information such as the file size or access permissions."
msgstr "尝试调用 fstat()（或等效函数）以确定文件大小或访问权限等信息时，VFS 层中发生了 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:349
msgid "A RAISE function within a trigger fired, causing the SQL statement to abort."
msgstr "一个触发器中的 RAISE 函数触发，导致 SQL 语句中止。"

#: ../rubisco/lib/sqlite_strerror.py:354
msgid "An I/O error within xUnlock method on the sqlite3_io_methods object."
msgstr "一个 sqlite3_io_methods 对象上的 xUnlock 方法中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:358
msgid "A UNIQUE constraint failed."
msgstr "一个 UNIQUE 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:361
msgid "I/O error within xLock method on the sqlite3_io_methods object while trying to obtain a read lock."
msgstr "在尝试获取读锁时，sqlite3_io_methods 对象上的 xLock 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:365
msgid "I/O error within xDelete method on the sqlite3_vfs object."
msgstr "在 sqlite3_vfs 对象上的 xDelete 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:367
msgid "A rowid is not unique."
msgstr "一个 rowid 不是唯一的。"

#: ../rubisco/lib/sqlite_strerror.py:373
msgid "An UPDATE trigger attempted do delete the row that was being updated in the middle of the update."
msgstr "一个 UPDATE 触发器尝试在更新过程中删除正在更新的行。"

#: ../rubisco/lib/sqlite_strerror.py:378
msgid "An operation could not be completed due to the inability to allocate sufficient memory."
msgstr "由于无法分配足够的内存，无法完成操作。"

#: ../rubisco/lib/sqlite_strerror.py:383
msgid "I/O error occured within the xAccess method on the sqlite3_vfs object."
msgstr "在 sqlite3_vfs 对象上的 xAccess 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:388
msgid "I/O error within the xCheckReservedLock method on the sqlite3_io_methods object."
msgstr "在 sqlite3_io_methods 对象上的 xCheckReservedLock 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:392
msgid "I/O error in the advisory file locking logic."
msgstr "咨询文件锁定逻辑中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:395
msgid "I/O error within the xClose method on the sqlite3_io_methods object."
msgstr "在 sqlite3_io_methods 对象上的 xClose 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:403
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to open a new shared memory segment."
msgstr "在尝试打开一个新的共享内存段时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:409
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to enlarge a \"shm\" file as part of WAL mode transaction processing. This error may indicate that the underlying filesystem volume is out of space."
msgstr "在尝试在 WAL 模式事务处理的一部分中扩大 \"shm\" 文件时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。此错误可能表示底层文件系统卷空间不足。"

#: ../rubisco/lib/sqlite_strerror.py:419
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to map a shared memory segment into the process address space."
msgstr "在尝试将共享内存段映射到进程地址空间时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:425
msgid "I/O error within the xRead or xWrite methods on the sqlite3_io_methods object while trying to seek a file descriptor to the beginning point of the file where the read or write is to occur."
msgstr "在尝试将文件描述符定位到读取或写入的文件的起始点时，sqlite3_io_methods 对象上的 xRead 或 xWrite 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:432
msgid "The xDelete method on the sqlite3_vfs object failed because the file being deleted does not exist."
msgstr "sqlite3_vfs 对象上的 xDelete 方法失败，因为要删除的文件不存在。"

#: ../rubisco/lib/sqlite_strerror.py:437
msgid "I/O error within the xFetch or xUnfetch methods on the sqlite3_io_methods object while trying to map or unmap part of the database file into the process address space."
msgstr "在尝试将数据库文件的一部分映射或取消映射到进程地址空间时，sqlite3_io_methods 对象上的 xFetch 或 xUnfetch 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:443
msgid "The VFS is unable to determine a suitable directory in which to place temporary files."
msgstr "VFS 无法确定一个合适的目录来放置临时文件。"

#: ../rubisco/lib/sqlite_strerror.py:447
msgid "The cygwin_conv_path() system call failed."
msgstr "cygwin_conv_path() 系统调用失败。"

#: ../rubisco/lib/sqlite_strerror.py:450
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_BEGIN_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_BEGIN_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/sqlite_strerror.py:455
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_COMMIT_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_COMMIT_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/sqlite_strerror.py:460
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/sqlite_strerror.py:464
msgid "The checksum on a page of the database file is incorrect."
msgstr "数据库文件的页面校验和不正确。"

#: ../rubisco/lib/sqlite_strerror.py:467
msgid "A seek or read failure was due to the request not falling within the file's boundary rather than an ordinary device failure."
msgstr "寻找或读取失败是由于请求不在文件的边界内，而不是普通的设备故障。"

#: ../rubisco/lib/sqlite_strerror.py:471
msgid "Unknown error code."
msgstr "未知错误代码。"

#: ../rubisco/lib/exceptions.py:112
msgid "Subprocess return code is ${{retcode}}."
msgstr "子进程返回代码为 ${{retcode}}。"

#: ../rubisco/lib/exceptions.py:118
msgid "Subprocess return code is ${{retcode}}. It may be caused by command not found."
msgstr "子进程返回代码为 ${{retcode}}。可能是由于未找到命令。"

#: ../rubisco/lib/archive/__init__.py:112 ../rubisco/lib/archive/sevenzip.py:58
#: ../rubisco/lib/archive/tar.py:84 ../rubisco/lib/archive/zip.py:66
msgid "Extracting ${{file}} to ${{path}} as '${{type}}' ..."
msgstr "正在以 '${{type}}' 格式解压 ${{file}} 到 ${{path}} ..."

#: ../rubisco/lib/archive/__init__.py:120 ../rubisco/lib/archive/sevenzip.py:68
#: ../rubisco/lib/archive/tar.py:92 ../rubisco/lib/archive/zip.py:74
msgid "Extracting"
msgstr "解压缩"

#: ../rubisco/lib/archive/__init__.py:224
msgid "Unable to guess compression type of ${{path}}."
msgstr "无法猜测 ${{path}} 的压缩类型。"

#: ../rubisco/lib/archive/__init__.py:229 ../rubisco/lib/archive/__init__.py:504
msgid "Please specify the compression type explicitly."
msgstr "请明确指定压缩类型。"

#: ../rubisco/lib/archive/__init__.py:245 ../rubisco/lib/archive/__init__.py:522
msgid "Unsupported compression type: ${{type}}"
msgstr "不支持的压缩类型： ${{type}}"

#: ../rubisco/lib/archive/__init__.py:249 ../rubisco/lib/archive/__init__.py:526
msgid "Supported types are 'gz', 'bz2', 'xz', 'zip', '7z', 'tar', 'tar.gz', 'tar.bz2', 'tar.xz'. You can also use the 'tgz', 'txz' and 'tbz2'."
msgstr "我们支持的类型有 'gz', 'bz2', 'xz', 'zip', '7z', 'tar', 'tar.gz', 'tar.bz2', 'tar.xz'。您也可以使用 'tgz', 'txz' 和 'tbz2'。"

#: ../rubisco/lib/archive/__init__.py:269
msgid "Failed to extract ${{file}} to ${{dest}}: ${{exc}}"
msgstr "解压 ${{file}} 到 ${{dest}} 时出错： ${{exc}}"

#: ../rubisco/lib/archive/__init__.py:333 ../rubisco/lib/archive/sevenzip.py:201
#: ../rubisco/lib/archive/tar.py:168 ../rubisco/lib/archive/zip.py:137
msgid "Compressing ${{path}} to ${{file}} as '${{type}}' ..."
msgstr "正在以 '${{type}}' 格式压缩 ${{path}} 到 ${{file}} ..."

#: ../rubisco/lib/archive/__init__.py:341 ../rubisco/lib/archive/utils.py:77
msgid "Compressing"
msgstr "压缩"

#: ../rubisco/lib/archive/__init__.py:499
msgid "Unable to determine compression type of ${{path}}."
msgstr "无法确定 ${{path}} 的压缩类型。"

#: ../rubisco/lib/archive/__init__.py:546
msgid "Failed to compress ${{src}} to ${{dest}}: ${{exc}}"
msgstr "压缩 ${{src}} 到 ${{dest}} 时出错： ${{exc}}"

#: ../rubisco/lib/archive/utils.py:93
msgid "${{path}} is not in the subpath of ${{start}}"
msgstr "${{path}} 不是 ${{start}} 的子路径"

#: ../rubisco/lib/process.py:135 ../rubisco/lib/process.py:194
msgid "Shell execution error."
msgstr "Shell 执行错误。"

#: ../rubisco/lib/fileutil.py:92
msgid "Absolute path ${{path}} is not allowed."
msgstr "不允许绝对路径 ${{path}} 。"

#: ../rubisco/lib/fileutil.py:118
msgid "Cannot remove root directory."
msgstr "无法删除根目录。"

#: ../rubisco/lib/fileutil.py:132
msgid "Error while removing ${{path}}: ${{error}}"
msgstr "删除 ${{path}} 时出错： ${{error}}"

#: ../rubisco/lib/fileutil.py:245
msgid "File ${{path}} already exists."
msgstr "文件 ${{path}} 已存在。"

#: ../rubisco/lib/fileutil.py:563
msgid "Invalid type: ${{path}}, expected file."
msgstr "${{path}} 不是一个文件。"

#: ../rubisco/lib/fileutil.py:573
msgid "Invalid type: ${{path}}, expected directory."
msgstr "${{path}} 不是一个目录。"

#: ../rubisco/lib/fileutil.py:680
msgid "Command '${{cmd}}' not found."
msgstr "命令 '${{cmd}}' 未找到。"

#: ../rubisco/lib/variable/fast_format_str.py:78
msgid "fast_format_str() only supports simple variable expressions."
msgstr "fast_format_str() 仅支持简单的变量表达式。"

#: ../rubisco/lib/variable/fast_format_str.py:84
msgid "fast_format_str() does not support default value."
msgstr "fast_format_str() 不支持默认值。"

#: ../rubisco/lib/variable/pyexpr_sandbox.py:48
#: ../rubisco/lib/variable/pyexpr_sandbox.py:112
msgid "<rubisco inline python expression>"
msgstr "<rubisco 内联 python 表达式>"

#: ../rubisco/lib/variable/pyexpr_sandbox.py:70
msgid "${{func}} is disallowed in Rubisco variable expression."
msgstr "${{func}} 在 Rubisco 变量表达式中不允许。"

#: ../rubisco/lib/variable/pyexpr_sandbox.py:125
msgid "Eval python expression failed: ${{expr}}: ${{exc}}"
msgstr "python 表达式求值失败： ${{expr}}: ${{exc}}"

#: ../rubisco/lib/variable/autoformatdict.py:119
msgid "The value of key ${{key}} needs to be ${{type}} instead of ${{value_type}}."
msgstr "键 ${{key}} 的值需要是 ${{type}} 类型而不是 ${{value_type}} 。"

#: ../rubisco/lib/variable/lexer.py:123 ../rubisco/lib/variable/lexer.py:162
#: ../rubisco/lib/variable/lexer.py:206
msgid "Invalid variable expression."
msgstr "不合法的变量表达式。"

#: ../rubisco/lib/variable/lexer.py:189
msgid "Invalid variable decorate expression."
msgstr "不合法的变量装饰表达式。"

#: ../rubisco/lib/variable/lexer.py:213
msgid "Invalid variable name."
msgstr "不合法的变量名称。"

#: ../rubisco/lib/variable/lexer.py:217
msgid "Variable name must only contain letters, numbers, and '-', '.', '_'."
msgstr "变量名只能包含字母、数字和 '-', '.', '_'。"

#: ../rubisco/lib/variable/execute.py:53
msgid "Undefined variable: ${{var}}"
msgstr "未定义的变量： ${{var}}"

#: ../rubisco/shared/ktrigger.py:733
msgid "Kernel trigger id '${{name}}' is already exists."
msgstr "Kernel trigger ID '${{name}}' 已经存在。"

#: ../rubisco/shared/extension.py:158
msgid "The extension '${{name}}' does not exist in workspace, user, or global extension directory."
msgstr "扩展 '${{name}}' 不存在于工作区、用户或全局扩展目录中。"

#: ../rubisco/shared/extension.py:163
msgid "Try to load the extension as a path."
msgstr "尝试将扩展作为路径加载。"

#: ../rubisco/shared/extension.py:178
msgid "The extension path ${{path}} does not exist."
msgstr "扩展路径 ${{path}} 不存在。"

#: ../rubisco/shared/extension.py:188
msgid "The extension ${{path}} does not have an instance."
msgstr "扩展 ${{path}} 没有实例。"

#: ../rubisco/shared/extension.py:194
msgid "Please make sure this extension is valid."
msgstr "请确保这个扩展是有效的。"

#: ../rubisco/shared/extension.py:290
msgid "Extension name '${{name}}' invalid."
msgstr "扩展名称 '${{name}}' 无效。"

#: ../rubisco/shared/extension.py:295
msgid "Extension name must be lowercase and only contain 0-9, a-z, A-Z, '_', '.' and '-'."
msgstr "扩展名称必须为小写，且只包含 0-9, a-z, A-Z, '_', '.' 和 '-'。"

#: ../rubisco/shared/extension.py:355
msgid "Failed to load extension '${{env}}/${{name}}': ${{exc}}"
msgstr "加载扩展 '${{env}}/${{name}}' 失败： ${{exc}}"

#: ../rubisco/cli/input.py:62
msgid "[yellow]Invalid input. Please enter '[green]Y[/green]' or '[red]N[/red]'."
msgstr "无效的输入。请输入 '[green]Y[/green]' 或 '[red]N[/red]'。"

#: ../rubisco/cli/input.py:69
msgid "Invalid input."
msgstr "无效的输入。"

#: ../rubisco/cli/main/main.py:78 ../rubisco/cli/main/ktrigger.py:897
msgid "Entering directory ${{path}} ..."
msgstr "正在进入目录 ${{path}} ..."

#: ../rubisco/cli/main/builtin_cmds.py:66
msgid "Default callback for showing Rubisco project infomation."
msgstr "显示 Rubisco 项目信息的默认回调函数。"

#: ../rubisco/cli/main/builtin_cmds.py:71 ../rubisco/cli/main/extman_cmds.py:327
msgid "Show project information."
msgstr "显示项目信息。"

#: ../rubisco/cli/main/project_config.py:78
#: ../rubisco/cli/main/project_config.py:148
msgid "Working directory ${{path}} is not a Rubisco project."
msgstr "工作目录 ${{path}} 不是一个 Rubisco 项目。"

#: ../rubisco/cli/main/project_config.py:128
msgid "Undefined command or hook ${{name}}."
msgstr "未定义的命令或钩子 ${{name}}。"

#: ../rubisco/cli/main/project_config.py:131
msgid "Perhaps a typo?"
msgstr "可能是拼写错误？"

#: ../rubisco/cli/main/project_config.py:153
msgid "${{path}} is not found."
msgstr "${{path}} 未找到。"

#: ../rubisco/cli/main/ktrigger.py:140
msgid "Executing: [cyan]${{cmd}}[/cyan] ..."
msgstr "正在执行： [cyan]${{cmd}}[/cyan] ..."

#: ../rubisco/cli/main/ktrigger.py:161
msgid "${{path}} already exists. [yellow]Overwrite[/yellow]?"
msgstr "${{path}} 已存在。[yellow]是否覆盖[/yellow]？"

#: ../rubisco/cli/main/ktrigger.py:269
msgid "Please install the following packages manually: [bold]${{packages}}[/bold]."
msgstr "请手动安装以下软件包： [bold]${{packages}}[/bold]。"

#: ../rubisco/cli/main/ktrigger.py:276
msgid "Continue anyway?"
msgstr "仍然继续吗？"

#: ../rubisco/cli/main/ktrigger.py:283
msgid "Updating Git repository ${{path}}(${{branch}}) ..."
msgstr "正在更新 Git 仓库 ${{path}}(${{branch}}) ..."

#: ../rubisco/cli/main/ktrigger.py:299
msgid "Cloning Git repository ${{url}} (${{branch}}) into ${{path}} ..."
msgstr "正在克隆 Git 仓库 ${{url}} (${{branch}}) 到 ${{path}} ..."

#: ../rubisco/cli/main/ktrigger.py:326
msgid "Testing ${{host}} ... ${{status}}"
msgstr "正在测试 ${{host}} ... ${{status}}"

#: ../rubisco/cli/main/ktrigger.py:336
msgid "Performing websites speed test ..."
msgstr "正在进行网站速度测试 ..."

#: ../rubisco/cli/main/ktrigger.py:340 ../rubisco/cli/main/ktrigger.py:362
msgid "[yellow]Testing[/yellow] ..."
msgstr "[yellow]测试中[/yellow] ..."

#: ../rubisco/cli/main/ktrigger.py:348
msgid "[red]Canceled[/red]"
msgstr "[red]已取消[/red]"

#: ../rubisco/cli/main/ktrigger.py:350
msgid "[red]Failed[/red]"
msgstr "[red]失败[/red]"

#: ../rubisco/cli/main/ktrigger.py:353
msgid "${{speed}} us"
msgstr "${{speed}} 微秒"

#: ../rubisco/cli/main/ktrigger.py:378
msgid "Selected mirror: ${{url}}"
msgstr "已选择镜像： ${{url}}"

#: ../rubisco/cli/main/ktrigger.py:388
msgid "Running: [white]${{name}}[/white] [black](${{id}})[/black]"
msgstr "正在运行： [white]${{name}}[/white] [black](${{id}})[/black]"

#: ../rubisco/cli/main/ktrigger.py:405
msgid "Running workflow: [white]${{name}}[/white] [black](${{id}})[/black]"
msgstr "正在运行工作流： [white]${{name}}[/white] [black](${{id}})[/black]"

#: ../rubisco/cli/main/ktrigger.py:418
msgid "Workflow '${{name}}' finished."
msgstr "工作流 '${{name}}' 完成。"

#: ../rubisco/cli/main/ktrigger.py:425
msgid "Running matrix jobs ..."
msgstr "正在运行矩阵作业 ..."

#: ../rubisco/cli/main/ktrigger.py:429
msgid "Running jobs with variables:"
msgstr "使用变量运行作业："

#: ../rubisco/cli/main/ktrigger.py:444
msgid "Creating directory: ${{path}} ..."
msgstr "正在创建目录： ${{path}} ..."

#: ../rubisco/cli/main/ktrigger.py:474
msgid "Moving file ${{src}} to ${{dst}} ..."
msgstr "正在移动文件 ${{src}} 到 ${{dst}} ..."

#: ../rubisco/cli/main/ktrigger.py:485
msgid "Copying ${{src}} to ${{dst}} ..."
msgstr "正在复制 ${{src}} 到 ${{dst}} ..."

#: ../rubisco/cli/main/ktrigger.py:496
msgid "Removing ${{path}} ..."
msgstr "正在移除 ${{path}} ..."

#: ../rubisco/cli/main/ktrigger.py:507
msgid "Selected: ${{path}}"
msgstr "已选择： ${{path}}"

#: ../rubisco/cli/main/ktrigger.py:523
msgid "Extension '${{name}}' loaded."
msgstr "扩展 '${{name}}' 已加载。"

#: ../rubisco/cli/main/ktrigger.py:532
msgid "[dark_orange]Rubisco CLI Language:[/dark_orange] '${{locale}}' '${{charset}}' '${{language_name}}'"
msgstr "[dark_orange]Rubisco CLI 语言：[/dark_orange] '${{locale}}' '${{charset}}' '${{language_name}}'"

#: ../rubisco/cli/main/ktrigger.py:544
msgid "[dark_orange]Project:[/dark_orange] ${{name}}"
msgstr "[dark_orange]项目：[/dark_orange] ${{name}}"

#: ../rubisco/cli/main/ktrigger.py:550
msgid "[dark_orange]Configuration:[/dark_orange] ${{path}}"
msgstr "[dark_orange]配置：[/dark_orange] ${{path}}"

#: ../rubisco/cli/main/ktrigger.py:557
msgid "[dark_orange]Version:[/dark_orange] v[white]${{version}}[/white]"
msgstr "[dark_orange]版本：[/dark_orange] v[white]${{version}}[/white]"

#: ../rubisco/cli/main/ktrigger.py:570
msgid "[dark_orange]Maintainers:[/dark_orange] ${{maintainers}}"
msgstr "[dark_orange]维护者：[/dark_orange] ${{maintainers}}"

#: ../rubisco/cli/main/ktrigger.py:574
msgid "[yellow]Unknown[/yellow]"
msgstr "[yellow]未知[/yellow]"

#: ../rubisco/cli/main/ktrigger.py:577
msgid "[dark_orange]License:[/dark_orange] ${{license}}"
msgstr "[dark_orange]许可证：[/dark_orange] ${{license}}"

#: ../rubisco/cli/main/ktrigger.py:583
msgid "[dark_orange]Description:[/dark_orange] ${{desc}}"
msgstr "[dark_orange]描述：[/dark_orange] ${{desc}}"

#: ../rubisco/cli/main/ktrigger.py:588
msgid "[dark_orange]Hooks:[/dark_orange]"
msgstr "[dark_orange]钩子：[/dark_orange]"

#: ../rubisco/cli/main/ktrigger.py:596
msgid "(${{num}} hooks)"
msgstr "(${{num}} 个钩子)"

#: ../rubisco/cli/main/ktrigger.py:613
msgid "Creating symbolic link: ${{src}} -> ${{dst}} ..."
msgstr "正在创建符号链接： ${{src}} -> ${{dst}} ..."

#: ../rubisco/cli/main/ktrigger.py:625
msgid "Creating hard link: ${{src}} -> ${{dst}} ..."
msgstr "正在创建硬链接： ${{src}} -> ${{dst}} ..."

#: ../rubisco/cli/main/ktrigger.py:638
msgid "Creating Rubisco extension environment: ${{path}} ..."
msgstr "正在创建 Rubisco 扩展环境： ${{path}}..."

#: ../rubisco/cli/main/ktrigger.py:652 ../rubisco/cli/main/ktrigger.py:700
#: ../rubisco/cli/main/ktrigger.py:748 ../rubisco/cli/main/ktrigger.py:795
#: ../rubisco/cli/main/extman_cmds.py:63
msgid "global"
msgstr "全局"

#: ../rubisco/cli/main/ktrigger.py:654 ../rubisco/cli/main/ktrigger.py:702
#: ../rubisco/cli/main/ktrigger.py:750 ../rubisco/cli/main/ktrigger.py:797
#: ../rubisco/cli/main/extman_cmds.py:65
msgid "user"
msgstr "用户"

#: ../rubisco/cli/main/ktrigger.py:656 ../rubisco/cli/main/ktrigger.py:704
#: ../rubisco/cli/main/ktrigger.py:752 ../rubisco/cli/main/ktrigger.py:799
#: ../rubisco/cli/main/extman_cmds.py:67
msgid "workspace"
msgstr "工作区"

#: ../rubisco/cli/main/ktrigger.py:660
msgid "Installing extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] to [yellow]${{dest}}[/yellow] (${{path}}) ..."
msgstr "正在安装扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 到 [yellow]${{dest}}[/yellow] (${{path}}) ..."

#: ../rubisco/cli/main/ktrigger.py:685
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully installed."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功安装。"

#: ../rubisco/cli/main/ktrigger.py:708
msgid "Uninstalling extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from [yellow]${{dest}}[/yellow] (${{path}}) ..."
msgstr "卸载扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 从 [yellow]${{dest}}[/yellow] (${{path}}) ..."

#: ../rubisco/cli/main/ktrigger.py:733
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully uninstalled."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功卸载。"

#: ../rubisco/cli/main/ktrigger.py:756
msgid "Upgrading extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from [yellow]${{dest}}[/yellow] (${{path}}) ..."
msgstr "正在从 [yellow]${{dest}}[/yellow] (${{path}}) 升级扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] ..."

#: ../rubisco/cli/main/ktrigger.py:781
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully upgraded."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功升级。"

#: ../rubisco/cli/main/ktrigger.py:802
msgid "The following extensions will be uninstalled from [yellow]${{dest}}[/yellow] (${{path}}):"
msgstr "以下扩展将从 [yellow]${{dest}}[/yellow] (${{path}}) 卸载："

#: ../rubisco/cli/main/ktrigger.py:818
msgid "Continue?"
msgstr "是否继续？"

#: ../rubisco/cli/main/ktrigger.py:911
msgid "Leaving directory ${{path}} ..."
msgstr "正在离开目录 ${{path}} ..."

#: ../rubisco/cli/main/version_action.py:43
msgid ""
"[bold]Copyright (C) 2025 [link=https://github.com/cppp-project]The C++ Plus Project[/link].[/bold]\n"
"License [bold]GPLv3+[/bold]: GNU GPL version [cyan]3[/cyan] or later <https://www.gnu.org/licenses/gpl.html>.\n"
"This is free software: you are free to change and redistribute it.\n"
"There is [yellow]NO WARRANTY[/yellow], to the extent permitted by law.\n"
"Written by [link=https://github.com/ChenPi11]ChenPi11[/link]."
msgstr ""
"[bold]版权所有 (C) 2025 [link=https://github.com/cppp-project]The C++ Plus Project[/link]。[/bold]\n"
"许可证 [bold]GPLv3+[/bold]：GNU GPL 许可证第[cyan]三[/cyan]版或者更高版本 <http://gnu.org/licenses/gpl.html>。\n"
"这是自由软件：你可以自由更改和重新发布它。\n"
"在法律许可的情况下特此明示，本软件[yellow]不提供任何担保[/yellow]。\n"
"由 [link=https://github.com/ChenPi11]ChenPi11[/link] 编写。"

#: ../rubisco/cli/main/version_action.py:68
msgid "Show program's version number and exit."
msgstr "显示程序的版本号并退出。"

#: ../rubisco/cli/main/arg_parser.py:67
msgid "Rubisco CommandEventFS Debugger CLI exited."
msgstr "Rubisco CommandEventFS Debugger CLI 已退出。"

#: ../rubisco/cli/main/arg_parser.py:91
msgid "Project root"
msgstr "项目根目录"

#: ../rubisco/cli/main/arg_parser.py:92
msgid "The root directory of Rubisco project."
msgstr "Rubisco 项目根目录。"

#: ../rubisco/cli/main/arg_parser.py:99
msgid "Used prompt colors (for CLI)."
msgstr "已使用的提示颜色 (仅为 CLI)"

#: ../rubisco/cli/main/arg_parser.py:101 ../rubisco/cli/main/arg_parser.py:270
msgid "Prompt colors used by rubisco parent process."
msgstr "rubisco 父进程使用的提示颜色。"

#: ../rubisco/cli/main/arg_parser.py:108
msgid "Enable Rubisco log"
msgstr "启用 Rubisco 日志"

#: ../rubisco/cli/main/arg_parser.py:110
msgid "Allow Rubisco to save log. Do not use this option directly. Use `--log` to allow Rubisco log. It will be saved to `.rubisco/rubisco.log`."
msgstr "允许 Rubisco 保存日志。不要直接使用此选项。使用 `--log` 允许 Rubisco 日志。它将保存到 `.rubisco/rubisco.log`。"

#: ../rubisco/cli/main/arg_parser.py:121
msgid "Allow Rubisco to save log."
msgstr "允许 Rubisco 保存日志。"

#: ../rubisco/cli/main/arg_parser.py:129
msgid "Enable debug mode."
msgstr "启用调试模式。"

#: ../rubisco/cli/main/arg_parser.py:131
msgid "Run rubisco in debug mode. Don't use this option directly. Use `--debug` to enable debug mode. It's parsed when Rubisco log system initializing."
msgstr "在调试模式下运行 rubisco。不要直接使用此选项。使用 `--debug` 启用调试模式。它在 Rubisco 日志系统初始化时解析。"

#: ../rubisco/cli/main/arg_parser.py:143
msgid "Run rubisco in debug mode."
msgstr "以调试模式运行 rubisco。"

#: ../rubisco/cli/main/arg_parser.py:151
msgid "Verbose"
msgstr "详细输出"

#: ../rubisco/cli/main/arg_parser.py:152 ../rubisco/cli/main/arg_parser.py:159
msgid "Enable verbose output."
msgstr "启用详细输出。"

#: ../rubisco/cli/main/arg_parser.py:170
msgid "Parse options in '/' and init Rubisco configs."
msgstr "在 '/' 中解析选项并初始化 Rubisco 配置。"

#: ../rubisco/cli/main/arg_parser.py:183
msgid "Show version."
msgstr "显示版本。"

#: ../rubisco/cli/main/arg_parser.py:189
msgid "Show Rubisco version."
msgstr "显示 Rubisco 版本。"

#: ../rubisco/cli/main/arg_parser.py:198
msgid "Launch CommandEventFS Debugger."
msgstr "启动 CommandEventFS Debugger。"

#: ../rubisco/cli/main/arg_parser.py:205
msgid "Launch Rubisco CommandEventFS Debugger CLI."
msgstr "启动 Rubisco CommandEventFS Debugger CLI。"

#: ../rubisco/cli/main/arg_parser.py:215
msgid "Extension directory."
msgstr "扩展目录。"

#: ../rubisco/cli/main/arg_parser.py:261
msgid "Project root directory."
msgstr "项目根目录。"

#: ../rubisco/cli/main/extman_cmds.py:69
msgid "foreign-package"
msgstr "外部包"

#: ../rubisco/cli/main/extman_cmds.py:70
msgid "unknown"
msgstr "未知"

#: ../rubisco/cli/main/extman_cmds.py:96
msgid "No environment exists or selected."
msgstr "不存在环境或已选择环境。"

#: ../rubisco/cli/main/extman_cmds.py:144
msgid "Package: [green]${{name}}[/green]"
msgstr "软件包： [green]${{name}}[/green]"

#: ../rubisco/cli/main/extman_cmds.py:151
msgid "Version: [cyan]${{ver}}[/cyan]"
msgstr "版本： [cyan]${{ver}}[/cyan]"

#: ../rubisco/cli/main/extman_cmds.py:158
msgid "Installation Location: ${{loc}}"
msgstr "安装位置： ${{loc}}"

#: ../rubisco/cli/main/extman_cmds.py:165
msgid "Maintainers: ${{maintainers}}"
msgstr "维护者： ${{maintainers}}"

#: ../rubisco/cli/main/extman_cmds.py:172
msgid "Homepage: ${{homepage}}"
msgstr "主页： ${{homepage}}"

#: ../rubisco/cli/main/extman_cmds.py:179
msgid "License: ${{license}}"
msgstr "许可证： ${{license}}"

#: ../rubisco/cli/main/extman_cmds.py:186
msgid "Tags: ${{tags}}"
msgstr "标签： ${{tags}}"

#: ../rubisco/cli/main/extman_cmds.py:193
msgid "Description: ${{desc}}"
msgstr "描述： ${{desc}}"

#: ../rubisco/cli/main/extman_cmds.py:224
msgid "No packages found."
msgstr "未找到软件包。"

#: ../rubisco/cli/main/extman_cmds.py:258
msgid "Invalid install destination: ${{dest}}. Supported destinations are 'workspace', 'user', 'global'."
msgstr "无效的安装目标： ${{dest}}。支持的目标是 'workspace', 'user', 'global'。"

#: ../rubisco/cli/main/extman_cmds.py:268
msgid "No files found."
msgstr "未找到文件。"

#: ../rubisco/cli/main/extman_cmds.py:299
msgid "Invalid uninstall destination: ${{dest}}. Supported destinations are 'workspace', 'user', 'global'."
msgstr "无效的卸载目标： ${{dest}}。支持的目标是 'workspace', 'user', 'global'。"

#: ../rubisco/cli/main/extman_cmds.py:314 ../rubisco/cli/main/extman_cmds.py:315
#: ../rubisco/cli/main/extman_cmds.py:400 ../rubisco/cli/main/extman_cmds.py:401
#: ../rubisco/cli/main/extman_cmds.py:542 ../rubisco/cli/main/extman_cmds.py:543
msgid "Packages matching patterns."
msgstr "匹配模式的软件包。"

#: ../rubisco/cli/main/extman_cmds.py:322
msgid "Default callback for list Rubisco extensions."
msgstr "列出 Rubisco 扩展的默认回调函数。"

#: ../rubisco/cli/main/extman_cmds.py:331 ../rubisco/cli/main/extman_cmds.py:332
#: ../rubisco/cli/main/extman_cmds.py:339 ../rubisco/cli/main/extman_cmds.py:417
#: ../rubisco/cli/main/extman_cmds.py:418 ../rubisco/cli/main/extman_cmds.py:425
msgid "Show workspace extensions."
msgstr "显示工作区扩展。"

#: ../rubisco/cli/main/extman_cmds.py:344 ../rubisco/cli/main/extman_cmds.py:430
msgid "Hide workspace extensions."
msgstr "隐藏工作区扩展。"

#: ../rubisco/cli/main/extman_cmds.py:352 ../rubisco/cli/main/extman_cmds.py:353
#: ../rubisco/cli/main/extman_cmds.py:360 ../rubisco/cli/main/extman_cmds.py:438
#: ../rubisco/cli/main/extman_cmds.py:439 ../rubisco/cli/main/extman_cmds.py:446
msgid "Show user extensions."
msgstr "显示用户扩展。"

#: ../rubisco/cli/main/extman_cmds.py:365 ../rubisco/cli/main/extman_cmds.py:451
msgid "Hide user extensions."
msgstr "隐藏用户扩展。"

#: ../rubisco/cli/main/extman_cmds.py:373 ../rubisco/cli/main/extman_cmds.py:374
#: ../rubisco/cli/main/extman_cmds.py:381 ../rubisco/cli/main/extman_cmds.py:459
#: ../rubisco/cli/main/extman_cmds.py:460 ../rubisco/cli/main/extman_cmds.py:467
msgid "Show global extensions."
msgstr "显示全局扩展。"

#: ../rubisco/cli/main/extman_cmds.py:386 ../rubisco/cli/main/extman_cmds.py:472
msgid "Hide global extensions."
msgstr "隐藏全局扩展。"

#: ../rubisco/cli/main/extman_cmds.py:408
msgid "Default callback for show Rubisco extensions."
msgstr "显示 Rubisco 扩展的默认回调函数。"

#: ../rubisco/cli/main/extman_cmds.py:413
msgid "Show extensions info with matching patterns."
msgstr "显示匹配模式的扩展信息。"

#: ../rubisco/cli/main/extman_cmds.py:486 ../rubisco/cli/main/extman_cmds.py:487
msgid "Extension package files glob patterns."
msgstr "扩展包文件 glob 模式字符串。"

#: ../rubisco/cli/main/extman_cmds.py:494
msgid "Default callback for install Rubisco extensions."
msgstr "安装 Rubisco 扩展的默认回调函数。"

#: ../rubisco/cli/main/extman_cmds.py:499
msgid "Install extensions with matching patterns."
msgstr "使用匹配模式安装扩展。"

#: ../rubisco/cli/main/extman_cmds.py:504
msgid "Install to destination."
msgstr "安装到目标。"

#: ../rubisco/cli/main/extman_cmds.py:506
msgid "Install extension packages to destination. support 'workspace', 'user', 'global'."
msgstr "安装扩展包到目标。支持 'workspace', 'user', 'global'。"

#: ../rubisco/cli/main/extman_cmds.py:515
msgid "Install to workspace."
msgstr "安装到工作区。"

#: ../rubisco/cli/main/extman_cmds.py:521
msgid "Install to user."
msgstr "安装到用户。"

#: ../rubisco/cli/main/extman_cmds.py:527
msgid "Install to global."
msgstr "安装到全局。"

#: ../rubisco/cli/main/extman_cmds.py:550
msgid "Default callback for uninstall Rubisco extensions."
msgstr "卸载 Rubisco 扩展的默认回调函数。"

#: ../rubisco/cli/main/extman_cmds.py:555
msgid "Uninstall extensions with matching patterns."
msgstr "卸载匹配模式的扩展。"

#: ../rubisco/cli/main/extman_cmds.py:559
msgid "Uninstall to destination."
msgstr "卸载到目标。"

#: ../rubisco/cli/main/extman_cmds.py:561
msgid "Uninstall extension packages to destination. support 'workspace', 'user', 'global'."
msgstr "卸载扩展包到目标。支持 'workspace', 'user', 'global'。"

#: ../rubisco/cli/main/extman_cmds.py:570
msgid "Uninstall to workspace."
msgstr "从工作区卸载。"

#: ../rubisco/cli/main/extman_cmds.py:576
msgid "Uninstall to user."
msgstr "从用户卸载。"

#: ../rubisco/cli/main/extman_cmds.py:582
msgid "Uninstall to global."
msgstr "从全局卸载。"

#: ../rubisco/cli/main/help_formatter.py:48
msgid "Show this help message and exit."
msgstr "显示此帮助消息并退出。"

#: ../rubisco/cli/main/help_formatter.py:54
#: ../rubisco/cli/cefs_dbg/helpmsg.py:149
msgid "Usage:"
msgstr "用法："

#: ../rubisco/cli/main/help_formatter.py:57
msgid "Positional Arguments:"
msgstr "位置参数："

#: ../rubisco/cli/main/help_formatter.py:60 ../rubisco/cli/cefs_dbg/cli.py:299
msgid "Options:"
msgstr "选项："

#: ../rubisco/cli/argparse_generator.py:137
msgid "The advanced options must be a list."
msgstr "高级选项必须是列表。"

#: ../rubisco/cli/argparse_generator.py:139
msgid "Advanced options must be a list of `dict[str, list[str] | int | str | None]`."
msgstr "高级选项必须是 `dict[str, list[str] | int | str | None]` 的列表。"

#: ../rubisco/cli/output.py:198
msgid "[red]Error: ${{msg}}[/red]"
msgstr "[red]错误： ${{msg}}[/red]"

#: ../rubisco/cli/output.py:211
msgid "[yellow]Warning: ${{msg}}[/yellow]"
msgstr "[yellow]警告： ${{msg}}[/yellow]"

#: ../rubisco/cli/output.py:226
msgid "[italic][magenta]Hint:[/magenta] ${{msg}}[/italic]"
msgstr "[italic][magenta]提示：[/magenta] ${{msg}}[/italic]"

#: ../rubisco/cli/output.py:256
msgid "Unknown error."
msgstr "未知错误。"

#: ../rubisco/cli/output.py:259 ../rubisco/envutils/packages.py:537
msgid "Interrupted by user."
msgstr "被用户中断。"

#: ../rubisco/cli/output.py:263
msgid "JSON5 decode error."
msgstr "JSON5 解码错误。"

#: ../rubisco/cli/output.py:265
msgid "Is may caused by a invalid JSON5 configuration file."
msgstr "可能是由于无效的 JSON5 配置文件。"

#: ../rubisco/cli/output.py:269
msgid "Missing key: ${{msg}}"
msgstr "找不到字典的键： ${{msg}}"

#: ../rubisco/cli/output.py:273
msgid "Is may caused by a invalid configuration file."
msgstr "可能是由于无效的配置文件。"

#: ../rubisco/cli/output.py:279
msgid "Internal error: ${{type}}: ${{msg}}"
msgstr "内部错误： ${{type}}： ${{msg}}"

#: ../rubisco/cli/output.py:287
msgid "See: ${{url}}"
msgstr "参见： ${{url}}"

#: ../rubisco/cli/cefs_dbg/cli.py:132
msgid "Command not found: ${{cmd}}"
msgstr "未找到命令： ${{cmd}}"

#: ../rubisco/cli/cefs_dbg/cli.py:150 ../rubisco/cli/cefs_dbg/cli.py:263
#: ../rubisco/cli/cefs_dbg/cli.py:292 ../rubisco/cli/cefs_dbg/cli.py:365
#: ../rubisco/cli/cefs_dbg/cli.py:419
msgid "Too many arguments."
msgstr "参数过多。"

#: ../rubisco/cli/cefs_dbg/cli.py:154
msgid "No such file or directory."
msgstr "没有这个文件或目录。"

#: ../rubisco/cli/cefs_dbg/cli.py:157
msgid "Not a directory."
msgstr "不是目录。"

#: ../rubisco/cli/cefs_dbg/cli.py:194 ../rubisco/cli/cefs_dbg/helpmsg.py:151
msgid "Arguments:"
msgstr "参数："

#: ../rubisco/cli/cefs_dbg/cli.py:198 ../rubisco/cli/cefs_dbg/cli.py:250
msgid "None."
msgstr "无。"

#: ../rubisco/cli/cefs_dbg/cli.py:200
msgid "Dynamic Arguments:"
msgstr "动态参数："

#: ../rubisco/cli/cefs_dbg/cli.py:204
msgid "From ${{mincount}} to ${{maxcount}}."
msgstr "从 ${{mincount}} 到 ${{maxcount}}。"

#: ../rubisco/cli/cefs_dbg/cli.py:210
msgid "unlimited"
msgstr "无限制"

#: ../rubisco/cli/cefs_dbg/cli.py:221 ../rubisco/cli/cefs_dbg/cli.py:237
#: ../rubisco/cli/cefs_dbg/cli.py:239
msgid "Unknown."
msgstr "未知。"

#: ../rubisco/cli/cefs_dbg/cli.py:224
msgid "Callbacks:"
msgstr "回调函数："

#: ../rubisco/cli/cefs_dbg/cli.py:230
msgid "Function: ${{repr}}"
msgstr "函数：${{repr}}"

#: ../rubisco/cli/cefs_dbg/cli.py:245
msgid "Source: ${{src}}"
msgstr "源码：${{src}}"

#: ../rubisco/cli/cefs_dbg/cli.py:260 ../rubisco/cli/cefs_dbg/cli.py:362
msgid "No file specified."
msgstr "未指定文件。"

#: ../rubisco/cli/cefs_dbg/cli.py:269 ../rubisco/cli/cefs_dbg/cli.py:371
msgid "No such file or directory: ${{path}}"
msgstr "没有这个文件或目录：${{path}}"

#: ../rubisco/cli/cefs_dbg/cli.py:274
msgid "Not a file."
msgstr "不是文件。"

#: ../rubisco/cli/cefs_dbg/cli.py:305 ../rubisco/cli/cefs_dbg/cli.py:396
msgid "Description: [yellow]${{description}}[/yellow]"
msgstr "描述：[yellow]${{description}}[/yellow]"

#: ../rubisco/cli/cefs_dbg/cli.py:312
msgid "Type: [green]${{type}}[/green]"
msgstr "类型：[green]${{type}}[/green]"

#: ../rubisco/cli/cefs_dbg/cli.py:320
msgid "Aliases: [blue]${{aliases}}[/blue]"
msgstr "别名：[blue]${{aliases}}[/blue]"

#: ../rubisco/cli/cefs_dbg/cli.py:328
msgid "Default value: ${{default}}"
msgstr "默认值： ${{default}}"

#: ../rubisco/cli/cefs_dbg/cli.py:336
msgid "Extra attributes: ${{ext_attributes}}"
msgstr "额外属性： ${{ext_attributes}}"

#: ../rubisco/cli/cefs_dbg/cli.py:347
msgid "Current value: ${{value}}"
msgstr "当前值： ${{value}}"

#: ../rubisco/cli/cefs_dbg/cli.py:384
msgid "File: ${{path}} ${{alias_to}}"
msgstr "文件：${{path}} ${{alias_to}}"

#: ../rubisco/cli/cefs_dbg/cli.py:390
msgid "Type: ${{type}}"
msgstr "类型：${{type}}"

#: ../rubisco/cli/cefs_dbg/cli.py:403
msgid "Mount point: ${{path}}"
msgstr "挂载点：${{path}}"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:47
msgid "Change the debugger's working directory."
msgstr "更改调试器的工作目录。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:51
msgid "Change the current directory to [italic]\\[PATH][/italic]. The default [italic]\\[PATH][/italic] is the root directory"
msgstr "将当前目录更改为 [italic]\\[PATH][/italic]。默认 [italic]\\[PATH][/italic] 是根目录"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:58
msgid "Display the file's data."
msgstr "显示文件数据。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:61
msgid "The file path to display."
msgstr "显示的文件路径。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:65
msgid "Display file or directory status."
msgstr "显示文件或目录状态。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:68
msgid "The file path to display status."
msgstr "显示状态的文件路径。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:72
msgid "List directory contents."
msgstr "列出目录内容。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:76
msgid "List the directory contents of [italic]\\[PATH][/italic]. The default [italic]\\[PATH][/italic] is the current directory"
msgstr "列出 [italic]\\[PATH][/italic] 的目录内容。默认 [italic]\\[PATH][/italic] 是当前目录"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:83
msgid "Exit the debugger."
msgstr "退出调试器。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:87
msgid "Display information about builtin commands."
msgstr "显示内置命令的信息。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:91
msgid "The command to display help information. If not specified, display help information about all builtin commands."
msgstr "用于显示帮助信息的命令。如果未指定，则显示有关所有内置命令的帮助信息。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:98
msgid "Clear the terminal screen and scrollback buffer."
msgstr "清除终端屏幕和滚动缓冲区。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:110
msgid "Command"
msgstr "命令"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:111
msgid "Description"
msgstr "描述"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:119
msgid "Use [green]help[/green] [bold]<COMMAND>[/] to get more help."
msgstr "使用 [green]help[/green] [bold]<COMMAND>[/] 来获取更多帮助。"

#: ../rubisco/cli/cefs_dbg/helpmsg.py:124
msgid "`help` use \"[italic][COMMAND][/italic]\" for optional arguments. Use \"[bold]<COMMAND>[/bold]\" for required arguments."
msgstr "`help` 使用 \"[italic][COMMAND][/italic]\" 表示可选参数。使用 \"[bold]<COMMAND>[/bold]\" 表示必需参数。"

#: ../rubisco/envutils/packages.py:112
msgid "'${{name}}' package must contain a directory with the same name as the package name and a '${{metafile}}' file."
msgstr "'${{name}}' 软件包必须包含一个与软件包名称相同的目录和一个 '${{metafile}}' 文件。"

#: ../rubisco/envutils/packages.py:131
msgid "'${{name}}' package contains files that not allowed in the root directory."
msgstr "'${{name}}' 软件包包含不允许在根目录中的文件。"

#: ../rubisco/envutils/packages.py:172
msgid "Package name '${{name}}' invalid."
msgstr "软件包名 '${{name}}' 无效。"

#: ../rubisco/envutils/packages.py:177
msgid "Package name must be lowercase and only contain 0-9, a-z, A-Z, '_', '.' and '-'."
msgstr "软件包名必须是小写的，只能包含 0-9，a-z，A-Z，'_'，'.' 和 '-'。"

#: ../rubisco/envutils/packages.py:192
msgid "Tags must be a list of strings."
msgstr "标签必须是字符串列表。"

#: ../rubisco/envutils/packages.py:199
msgid "Tags must be lowercase and only contain 0-9, a-z, A-Z, '_' and '-'."
msgstr "标签必须是小写的，只能包含 0-9，a-z，A-Z，'_' 和 '-'。"

#: ../rubisco/envutils/packages.py:220
msgid "${{path}} package configuration file is not a valid JSON5 file."
msgstr "${{path}} 软件包配置文件不是有效的 JSON5 文件。"

#: ../rubisco/envutils/packages.py:230
msgid "${{path}} package configuration file is missing a required key: ${{key}}."
msgstr "${{path}} 软件包配置文件缺少必需的键：'${{key}}'。"

#: ../rubisco/envutils/packages.py:272
msgid "${{path}} is not a valid Rubisco extension package."
msgstr "${{path}} 不是有效的 Rubisco 扩展包。"

#: ../rubisco/envutils/packages.py:276
msgid "Rubisco extension package must be a zip file."
msgstr "Rubisco 扩展包必须是一个 zip 文件。"

#: ../rubisco/envutils/packages.py:284
msgid "Error while opening ${{metafile}} in ${{path}}: '${{msg}}'."
msgstr "打开 ${{metafile}} 在 ${{path}} 时出错：'${{msg}}'。"

#: ../rubisco/envutils/packages.py:297
msgid "${{path}} package configuration file is missing a required key: '${{key}}'."
msgstr "${{path}} 软件包配置文件缺少必需的键：'${{key}}'。"

#: ../rubisco/envutils/packages.py:328
msgid "Multiple instances of '${{name}}' extension found in the database. Selecting the last one."
msgstr "在数据库中找到多个 '${{name}}' 扩展的实例。选择最后一个。"

#: ../rubisco/envutils/packages.py:403
msgid "${{path}} already exists in the filesystem."
msgstr "${{path}} 已存在于文件系统中。"

#: ../rubisco/envutils/packages.py:454
msgid "No extension installed."
msgstr "未安装任何扩展。"

#: ../rubisco/envutils/packages.py:462
msgid "No extension found matching '${{pattern}}'."
msgstr "未找到与 '${{pattern}}' 匹配的扩展。"

#: ../rubisco/envutils/packages.py:473
msgid "Selected '${{name}}'."
msgstr "已选择 '${{name}}'。"

#: ../rubisco/envutils/packages.py:494
msgid "Extension '${{name}}'(${{path}}) is not found in the filesystem."
msgstr "扩展 '${{name}}'(${{path}}) 未找到。"

#: ../rubisco/envutils/packages.py:576 ../rubisco/envutils/packages.py:645
msgid "The same version of '${{name}}' extension is already installed."
msgstr "已安装了 '${{name}}' 扩展的相同版本。"

#: ../rubisco/envutils/packages.py:588 ../rubisco/envutils/packages.py:657
msgid "The higher version of '${{name}}' extension is already installed."
msgstr "已安装了 '${{name}}' 扩展的更高版本。"

#: ../rubisco/envutils/packages.py:627
msgid "Rubisco Binary Package (RuBP) '${{path}}' must be a zipfile with '.rubp' suffix."
msgstr "Rubisco 二进制软件包 (RuBP) '${{path}}' 必须是一个 zip 文件，后缀名为 '.rubp'。"

#: ../rubisco/envutils/env.py:118
msgid "The database ${{path}} is broken."
msgstr "数据库 ${{path}} 已损坏。"

#: ../rubisco/envutils/env.py:125
msgid "Failed to check the environment."
msgstr "检查环境时出错。"

#: ../rubisco/envutils/env.py:128
msgid "The ${{path}} is not a valid venv but exists.Please remove it and try again."
msgstr "${{path}} 不是一个有效的 venv，但存在。请删除它并重试。"

#: ../rubisco/envutils/env.py:149
msgid "Failed to create venv. Consider to check thepermissions of the path."
msgstr "创建 venv 时出错。请检查路径的权限。"

#: ../rubisco/envutils/env.py:157
msgid "Failed to create the database for the environment."
msgstr "创建环境数据库时出错。"

#: ../rubisco/envutils/env.py:209
msgid "Waiting for the environment to be unlocked (${{path}}): ${{seconds}} seconds."
msgstr "等待环境解锁 (${{path}})： ${{seconds}} 秒。"

#: ../rubisco/envutils/env.py:255
msgid "The environment ${{path}} is already locked by PID ${{pid}}. If you want to force unlock it, please remove the lock file ${{lockfile}} manually."
msgstr "环境 ${{path}} 已被 PID ${{pid}} 锁定。如果您想强制解锁它，请手动删除锁文件 ${{lockfile}}。"

#: ../rubisco/envutils/env.py:271
msgid "The PID '${{pid}}' is not valid. Maybe the process has already exited. Remove the lock file if you believe the process has already exited."
msgstr "PID '${{pid}}' 无效。可能进程已经退出。如果您相信进程已经退出，请手动删除锁文件。"

#: ../rubisco/envutils/env.py:303
msgid "The lock file ${{path}} is broken."
msgstr "锁文件 ${{path}} 已损坏。"

#: ../rubisco/envutils/env.py:317
msgid "Failed to read the lock file ${{path}}: ${{msg}}"
msgstr "读取锁文件 ${{path}} 时出错： ${{msg}}"

#: ../rubisco/envutils/env.py:375
msgid "The environment ${{path}} is locked by another thread (PID ${{pid}}, Thread ${{thread}}). Unlock request is ignored."
msgstr "环境 ${{path}} 由另一个线程 (PID ${{pid}}, Thread ${{thread}}) 锁定。忽略解锁请求。"

#: ../rubisco/envutils/env.py:395
msgid "Failed to unlock the extension environment ${{path}}: ${{msg}}"
msgstr "解锁扩展环境 ${{path}} 时出错： ${{msg}}"

#: ../rubisco/envutils/env_db.py:142
msgid "[SQLite3 Errorcode ${{codename}}(${{code}})]: ${{msg}}"
msgstr "[SQLite3 错误代码 ${{codename}}(${{code}})]：${{msg}}"

#: ../rubisco/envutils/env_db.py:155
msgid "Failed to open or operate on database ${{path}}: ${{exc}}"
msgstr "打开或操作数据库 ${{path}} 时出错： ${{exc}}"

#: ../rubisco/envutils/env_db.py:290
msgid "Invalid regex pattern: '${{pattern}}'."
msgstr "无效的正则表达式: '${{pattern}}'。"

#: ../rubisco/envutils/utils.py:79
msgid "Failed to add ${{path}} to sys.path: ${{exc}}"
msgstr "添加 ${{path}} 到 sys.path 失败： ${{exc}}"

#: ../rubisco/envutils/pip.py:78
msgid "You are installing a extension to the global environment. Please make sure that you have the right permissions."
msgstr "您正在安装一个扩展到全局环境。请确保您具有正确的权限。"

#: /usr/lib/python3.13/argparse.py:227
#, python-format
msgid "%(heading)s:"
msgstr "%(heading)s:"

#: /usr/lib/python3.13/argparse.py:300
msgid "usage: "
msgstr "用法："

#: /usr/lib/python3.13/argparse.py:676
#, python-format
msgid " (default: %(default)s)"
msgstr " （默认值：%(default)s）"

#: /usr/lib/python3.13/argparse.py:738
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr "参数 %(argument_name)s: %(message)s"

#: /usr/lib/python3.13/argparse.py:847
msgid ".__call__() not defined"
msgstr ".__call__() 未定义"

#: /usr/lib/python3.13/argparse.py:1138
msgid "show program's version number and exit"
msgstr "显示程序的版本号并退出"

#: /usr/lib/python3.13/argparse.py:1201
#, python-format
msgid "conflicting subparser: %s"
msgstr "冲突的子解析器: %s"

#: /usr/lib/python3.13/argparse.py:1205
#, python-format
msgid "conflicting subparser alias: %s"
msgstr "冲突的子解析器别名: %s"

#: /usr/lib/python3.13/argparse.py:1244
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr "未知的解析器 %(parser_name)r (可选项: %(choices)s)"

#: /usr/lib/python3.13/argparse.py:1248
#, python-format
msgid "command '%(parser_name)s' is deprecated"
msgstr "命令 '%(parser_name)s' 已弃用"

#: /usr/lib/python3.13/argparse.py:1309
#, python-format
msgid "argument \"-\" with mode %r"
msgstr "参数 \"-\" 的模式 %r"

#: /usr/lib/python3.13/argparse.py:1318
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr "无法打开 '%(filename)s': %(error)s"

#: /usr/lib/python3.13/argparse.py:1532
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr "无法合并操作 - 两个组都命名为 %r"

#: /usr/lib/python3.13/argparse.py:1574
msgid "'required' is an invalid argument for positionals"
msgstr "'required' 是位置参数的无效参数"

#: /usr/lib/python3.13/argparse.py:1595
#, python-format
msgid "invalid option string %(option)r: must start with a character %(prefix_chars)r"
msgstr "无效的选项字符串 %(option)r: 必须以字符 %(prefix_chars)r 开头"

#: /usr/lib/python3.13/argparse.py:1613
#, python-format
msgid "dest= is required for options like %r"
msgstr "对于 %r 这样的选项，需要 dest="

#: /usr/lib/python3.13/argparse.py:1630
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr "无效的 conflict_resolution 值: %r"

#: /usr/lib/python3.13/argparse.py:1648
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] "冲突的选项字符串: %s"
msgstr[1] "冲突的选项字符串: %s"

#: /usr/lib/python3.13/argparse.py:1723
msgid "mutually exclusive arguments must be optional"
msgstr "互斥参数必须是可选的"

#: /usr/lib/python3.13/argparse.py:1800
msgid "positional arguments"
msgstr "位置参数"

#: /usr/lib/python3.13/argparse.py:1801
msgid "options"
msgstr "选项"

#: /usr/lib/python3.13/argparse.py:1816
msgid "show this help message and exit"
msgstr "显示此帮助消息并退出"

#: /usr/lib/python3.13/argparse.py:1847
msgid "cannot have multiple subparser arguments"
msgstr "不能有多个子解析器参数"

#: /usr/lib/python3.13/argparse.py:1853
msgid "subcommands"
msgstr "子命令"

#: /usr/lib/python3.13/argparse.py:1900 /usr/lib/python3.13/argparse.py:2463
#, python-format
msgid "unrecognized arguments: %s"
msgstr "未识别的参数：%s"

#: /usr/lib/python3.13/argparse.py:2006
#, python-format
msgid "not allowed with argument %s"
msgstr "不允许与参数 %s 一起使用"

#: /usr/lib/python3.13/argparse.py:2025
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr "不明确的选项: %(option)s 可能匹配 %(matches)s"

#: /usr/lib/python3.13/argparse.py:2057 /usr/lib/python3.13/argparse.py:2089
#, python-format
msgid "ignored explicit argument %r"
msgstr "忽略显式参数 %r"

#: /usr/lib/python3.13/argparse.py:2109
#, python-format
msgid "option '%(option)s' is deprecated"
msgstr "选项 '%(option)s' 已弃用"

#: /usr/lib/python3.13/argparse.py:2141
#, python-format
msgid "argument '%(argument_name)s' is deprecated"
msgstr "%(argument_name)s 参数已弃用"

#: /usr/lib/python3.13/argparse.py:2234
#, python-format
msgid "the following arguments are required: %s"
msgstr "需要以下参数: %s"

#: /usr/lib/python3.13/argparse.py:2249
#, python-format
msgid "one of the arguments %s is required"
msgstr "需要其中一个参数 %s"

#: /usr/lib/python3.13/argparse.py:2293
msgid "expected one argument"
msgstr "预期一个参数"

#: /usr/lib/python3.13/argparse.py:2294
msgid "expected at most one argument"
msgstr "预期最多一个参数"

#: /usr/lib/python3.13/argparse.py:2295
msgid "expected at least one argument"
msgstr "预期至少一个参数"

#: /usr/lib/python3.13/argparse.py:2299
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] "预期 %s 个参数"
msgstr[1] "预期 %s 个参数"

#: /usr/lib/python3.13/argparse.py:2409
#, python-format
msgid "unexpected option string: %s"
msgstr "意外的选项字符串: %s"

#: /usr/lib/python3.13/argparse.py:2546
#, python-format
msgid "%r is not callable"
msgstr "%r 不是可调用的"

#: /usr/lib/python3.13/argparse.py:2562
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr "无效的 %(type)s 值: %(value)r"

#: /usr/lib/python3.13/argparse.py:2577
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr "无效的选择: %(value)r (可选项为 %(choices)s)"

#: /usr/lib/python3.13/argparse.py:2658
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr "%(prog)s: 错误: %(message)s\n"

#: /usr/lib/python3.13/argparse.py:2662
#, python-format
msgid "%(prog)s: warning: %(message)s\n"
msgstr "%(prog)s: 警告: %(message)s\n"

#~ msgid "'${{name}}' package must contain a directory with the same name as the package name and a 'rubisco.json' file."
#~ msgstr "'${{name}}' 软件包必须包含一个与软件包名称相同的目录和一个 'rubisco.json' 文件。"

#~ msgid "A workflow [yellow]SHOULD[/yellow] contain at least 'exec', 'run' and 'workflow'."
#~ msgstr "工作流 [yellow]应该[/yellow]至少包含 'exec'， 'run' 和 'workflow' 选项。"

#~ msgid "Circular dependency detected: ${{path}}."
#~ msgstr "检测到循环依赖： ${{path}}。"

#~ msgid "Debug mode"
#~ msgstr "调试模式"

#~ msgid "Error while opening [underline]rubisco.json[/underline] in ${{path}}: '${{msg}}'."
#~ msgstr "打开 [underline]rubisco.json[/underline] 时出错： '${{msg}}'。"

#~ msgid "Failed to load extension ${{path}}."
#~ msgstr "加载扩展 ${{path}} 失败。"

#~ msgid "Failed to load extension '${{name}}': ${{exc}}"
#~ msgstr "加载扩展 '${{name}}' 失败： ${{exc}}"

#~ msgid "Install extension packages to global."
#~ msgstr "将扩展包安装到全局。"

#~ msgid "Install extension packages to user."
#~ msgstr "将扩展包安装到用户。"

#~ msgid "Install extension packages to workspace."
#~ msgstr "将扩展包安装到工作区。"

#~ msgid "Invalid path ${{path}}."
#~ msgstr "无效的路径 ${{path}}。"

#~ msgid "Log file"
#~ msgstr "日志文件"

#~ msgid "Maintainers must be a list of strings."
#~ msgstr "Maintainers 必须是字符串列表。"

#~ msgid "Maintainers must not contain ','."
#~ msgstr "Maintainers 不能包含 ','。"

#~ msgid "The advanced options action must be a string."
#~ msgstr "高级选项的 action 项必须是字符串。"

#~ msgid "The advanced options description must be a string."
#~ msgstr "高级选项的 description 项必须是字符串。"

#~ msgid "The configuration file must be a JSON5 object."
#~ msgstr "配置文件必须是一个 JSON5 对象。"

#~ msgid "The file path for saving log."
#~ msgstr "日志保存的文件路径。"

#~ msgid "Uninstall extension packages from global."
#~ msgstr "从全局卸载扩展。"

#~ msgid "Uninstall extension packages from user."
#~ msgstr "从用户卸载扩展。"

#~ msgid "Uninstall extension packages from workspace."
#~ msgstr "从工作区卸载扩展。"

#~ msgid "Uninstall from global."
#~ msgstr "从全局卸载。"

#~ msgid "Uninstall from user."
#~ msgstr "从用户卸载。"

#~ msgid "Uninstall from workspace."
#~ msgstr "从工作区卸载。"

#~ msgid "Workflow variables must be a list of name and value."
#~ msgstr "工作流变量必须是名称和值的列表。"

#~ msgid "You must specify only one install destination."
#~ msgstr "你必须指定一个安装位置。"

#~ msgid "You must specify only one uninstall destination."
#~ msgstr "你必须指定一个卸载位置。"

#~ msgid "[dark_orange]Maintainer:[/dark_orange] ${{maintainer}}"
#~ msgstr "[dark_orange]维护者：[/dark_orange] ${{maintainer}}"

#~ msgid "[yellow]Compressing[/yellow]"
#~ msgstr "[yellow]压缩中[/yellow]"

#~ msgid "[yellow]Downloading[/yellow]"
#~ msgstr "[yellow]下载中[/yellow]"

#~ msgid "[yellow]Extracting[/yellow]"
#~ msgstr "[yellow]解压中[/yellow]"

#~ msgid "[yellow]Processing[/yellow]"
#~ msgstr "[yellow]处理中[/yellow]"
